### ISSUE TITLE
how to run power example?

### ISSUE THREAD

**Issue by jasmainak** [neuropycon/ephypype#31]
I get the following error on the [power example](https://neuropycon.github.io/neuropycon_doc/examples/power_example.html):

```py
In [1]: %run plot_power.py
*** main_path -> /home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega ***
180914-23:59:07,341 nipype.workflow INFO:
	 Generated workflow graph: /home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/power_pipeline/graph.png (graph2use=colored, simple_form=True).
180914-23:59:07,351 nipype.workflow INFO:
	 Workflow power_pipeline settings: ['check', 'execution', 'logging', 'monitoring']
180914-23:59:07,355 nipype.workflow INFO:
	 Running in parallel.
180914-23:59:07,357 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 27.95/27.95, Free processors: 3/3.
180914-23:59:07,430 nipype.workflow INFO:
	 [Node] Setting-up "power_pipeline.datasource" in "/home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/power_pipeline/_sess_index_ses-0001_subject_id_sub-0003/datasource".
180914-23:59:07,436 nipype.workflow INFO:
	 [Node] Running "datasource" ("nipype.interfaces.io.DataGrabber")
180914-23:59:07,441 nipype.workflow WARNING:
	 [Node] Error on "power_pipeline.datasource" (/home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/power_pipeline/_sess_index_ses-0001_subject_id_sub-0003/datasource)
180914-23:59:09,389 nipype.workflow ERROR:
	 Node datasource.a0 failed to run on host mainak-ThinkPad-W540.
180914-23:59:09,389 nipype.workflow ERROR:
	 Saving crash info to /home/mainak/Desktop/projects/github_repos/ephypype/examples/crash-20180914-235909-mainak-datasource.a0-06204c04-801f-4abc-9648-ced9e5624c68.pklz
Traceback (most recent call last):
  File "/home/mainak/anaconda2/lib/python2.7/site-packages/nipype-1.1.2-py2.7.egg/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/mainak/anaconda2/lib/python2.7/site-packages/nipype-1.1.2-py2.7.egg/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/home/mainak/anaconda2/lib/python2.7/site-packages/nipype-1.1.2-py2.7.egg/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/home/mainak/anaconda2/lib/python2.7/site-packages/nipype-1.1.2-py2.7.egg/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/mainak/anaconda2/lib/python2.7/site-packages/nipype-1.1.2-py2.7.egg/nipype/interfaces/base/core.py", line 523, in run
    outputs = self.aggregate_outputs(runtime)
  File "/home/mainak/anaconda2/lib/python2.7/site-packages/nipype-1.1.2-py2.7.egg/nipype/interfaces/base/core.py", line 597, in aggregate_outputs
    predicted_outputs = self._list_outputs()
  File "/home/mainak/anaconda2/lib/python2.7/site-packages/nipype-1.1.2-py2.7.egg/nipype/interfaces/io.py", line 1259, in _list_outputs
    raise IOError(msg)
IOError: Output key: raw_file Template: /home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/*sub-0003/ses-0001/meg/sub-0003*rest*ica.fif returned no files

180914-23:59:09,396 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 27.95/27.95, Free processors: 3/3.
180914-23:59:11,361 nipype.workflow INFO:
	 ***********************************
180914-23:59:11,361 nipype.workflow ERROR:
	 could not run node: power_pipeline.datasource.a0
180914-23:59:11,361 nipype.workflow INFO:
	 crashfile: /home/mainak/Desktop/projects/github_repos/ephypype/examples/crash-20180914-235909-mainak-datasource.a0-06204c04-801f-4abc-9648-ced9e5624c68.pklz
180914-23:59:11,361 nipype.workflow INFO:
	 ***********************************
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/home/mainak/Desktop/projects/github_repos/ephypype/examples/plot_power.py in <module>()
     84     main_workflow.config['execution'] = {'remove_unnecessary_outputs': 'false'}
     85 
---> 86     main_workflow.run(plugin='MultiProc', plugin_args={'n_procs': 3})

/home/mainak/anaconda2/lib/python2.7/site-packages/nipype-1.1.2-py2.7.egg/nipype/pipeline/engine/workflows.pyc in run(self, plugin, plugin_args, updatehash)
    593         if str2bool(self.config['execution']['create_report']):
    594             self._write_report_info(self.base_dir, self.name, execgraph)
--> 595         runner.run(execgraph, updatehash=updatehash, config=self.config)
    596         datestr = datetime.utcnow().strftime('%Y%m%dT%H%M%S')
    597         if str2bool(self.config['execution']['write_provenance']):

/home/mainak/anaconda2/lib/python2.7/site-packages/nipype-1.1.2-py2.7.egg/nipype/pipeline/plugins/base.pyc in run(self, graph, config, updatehash)
    190 
    191         self._remove_node_dirs()
--> 192         report_nodes_not_run(notrun)
    193 
    194         # close any open resources

/home/mainak/anaconda2/lib/python2.7/site-packages/nipype-1.1.2-py2.7.egg/nipype/pipeline/plugins/tools.pyc in report_nodes_not_run(notrun)
     80                 logger.debug(subnode._id)
     81         logger.info("***********************************")
---> 82         raise RuntimeError(('Workflow did not execute cleanly. '
     83                             'Check log for details'))
     84 

RuntimeError: Workflow did not execute cleanly. Check log for details
```

@annapasca it's asking for `ica` files. Where do I get them from?

**Comment by annapasca** [comment]
`Output key: raw_file Template: /home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/*sub-0003/ses-0001/meg/sub-0003*rest*ica.fif returned no file`

I put sub-0003_task-rest_run-01_meg_raw_filt_dsamp_ica.fif in the Dropbox :)

**Comment by jasmainak** [comment]
hmm ... now my script is stuck. Output so far.

```py
In [1]: %run examples/plot_02_power.py
*** main_path -> /home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega ***
180916-22:30:49,489 nipype.workflow INFO:
	 Generated workflow graph: /home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/power_pipeline/graph.png (graph2use=colored, simple_form=True).
180916-22:30:49,630 nipype.workflow INFO:
	 Workflow power_pipeline settings: ['check', 'execution', 'logging', 'monitoring']
180916-22:30:49,687 nipype.workflow INFO:
	 Running in parallel.
180916-22:30:49,704 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 27.95/27.95, Free processors: 3/3.
180916-22:30:49,788 nipype.workflow INFO:
	 [Node] Setting-up "power_pipeline.datasource" in "/home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/power_pipeline/_sess_index_ses-0001_subject_id_sub-0003/datasource".
180916-22:30:49,812 nipype.workflow INFO:
	 [Node] Running "datasource" ("nipype.interfaces.io.DataGrabber")
180916-22:30:49,823 nipype.workflow INFO:
	 [Node] Finished "power_pipeline.datasource".
180916-22:30:51,694 nipype.workflow INFO:
	 [Job 0] Completed (power_pipeline.datasource).
180916-22:30:51,698 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 27.95/27.95, Free processors: 3/3.
180916-22:30:51,776 nipype.workflow INFO:
	 [Node] Setting-up "power_pipeline.power.power" in "/home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/power_pipeline/power/_sess_index_ses-0001_subject_id_sub-0003/power".
180916-22:30:51,814 nipype.workflow INFO:
	 [Node] Running "power" ("ephypype.interfaces.mne.power.Power")
in Power
Opening raw data file /home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/sub-0003/ses-0001/meg/sub-0003_task-rest_run-01_meg_raw_filt_dsamp_ica.fif...
ephypype/power.py:18: RuntimeWarning: This filename (/home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/sub-0003/ses-0001/meg/sub-0003_task-rest_run-01_meg_raw_filt_dsamp_ica.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
  epochs = read_raw_fif(data_fname, preload=True)
This filename (/home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/sub-0003/ses-0001/meg/sub-0003_task-rest_run-01_meg_raw_filt_dsamp_ica.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
    Read 5 compensation matrices
    Range : 0 ... 479999 =      0.000 ...   599.999 secs
Ready.
Current compensation grade : 3
Reading 0 ... 479999  =      0.000 ...   599.999 secs...
180916-22:30:53,694 nipype.workflow INFO:
	 [MultiProc] Running 1 tasks, and 0 jobs ready. Free memory (GB): 27.75/27.95, Free processors: 2/3.                     
                     Currently running:
                       * power_pipeline.power.power
Effective window size : 0.320 (s)
(270, 48)
*** save /home/mainak/Desktop/projects/github_repos/BIDS-examples/sample_BIDS_omega/power_pipeline/power/_sess_index_ses-0001_subject_id_sub-0003/power/sub-0003_task-rest_run-01_meg_raw_filt_dsamp_ica-psds.npz ***
```

**Comment by annapasca** [comment]
HI @jasmainak I have just run the power analysis and it works for me. I don't understand the problem.

@davidmeunier79 @dmalt some idea?

**Comment by annapasca** [comment]
```
(mne) pasca@pasca-XPS-13-9360:~/Tools/python/packages/neuropycon/examples$ conda list
# packages in environment at /home/pasca/anaconda3/envs/mne:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.11                   py36_0  
apipkg                    1.5                       <pip>
appdirs                   1.4.3            py36h28b3542_0  
apptools                  4.4.0                     <pip>
asn1crypto                0.24.0                   py36_0  
astroid                   2.0.4                    py36_0  
atomicwrites              1.2.1                    py36_0  
attrs                     18.2.0           py36h28b3542_0  
automat                   0.7.0                    py36_0  
babel                     2.6.0                    py36_0  
backcall                  0.1.0                    py36_0  
blas                      1.0                         mkl  
bleach                    2.1.4                    py36_0  
ca-certificates           2018.03.07                    0  
certifi                   2018.8.24                py36_1  
cffi                      1.11.5           py36he75722e_1  
chardet                   3.0.4                    py36_1  
click                     6.7                       <pip>
cloudpickle               0.5.5                    py36_0  
codespell                 1.13.0                    <pip>
configobj                 5.0.6                     <pip>
configparser              3.5.0                     <pip>
constantly                15.1.0           py36h28b3542_0  
coverage                  4.5.1            py36h14c3975_0  
cryptography              2.3.1            py36hc365091_0  
cycler                    0.10.0                   py36_0  
cython                    0.28.5           py36hf484d3e_0  
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py36_0  
dipy                      0.14.0                    <pip>
docutils                  0.14                     py36_0  
entrypoints               0.2.3                    py36_2  
envisage                  4.7.0                     <pip>
ephypype                  0.1.dev0                  <pip>
execnet                   1.5.0                     <pip>
expat                     2.2.6                he6710b0_0  
flake8                    3.5.0                    py36_1  
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8                  hab7d2ae_1  
funcsigs                  1.0.2                     <pip>
future                    0.16.0                   py36_0  
glib                      2.56.2               hd408876_0  
gmp                       6.1.2                h6c8ec71_1  
graphpype                 0.0.2                     <pip>
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.8.0            py36h39dcb92_0  
hdf5                      1.8.18               h6792536_1  
html5lib                  1.0.1                    py36_0  
hyperlink                 18.0.0                   py36_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.7                      py36_0  
imagesize                 1.1.0                    py36_0  
incremental               17.5.0                   py36_0  
intel-openmp              2018.0.3                      0  
ipykernel                 4.9.0                    py36_0  
ipython                   6.5.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                7.4.1                    py36_0  
isodate                   0.6.0                     <pip>
isort                     4.3.4                    py36_0  
jedi                      0.12.1                   py36_0  
jeepney                   0.3.1                    py36_0  
jinja2                    2.10                     py36_0  
joblib                    0.12.3                   py36_0  
jpeg                      9b                   h024ee3a_2  
jsoncpp                   1.8.3                h3a67955_0  
jsonschema                2.6.0                    py36_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0                    py36_1  
jupyter_core              4.4.0                    py36_0  
keyring                   13.2.1                   py36_0  
kiwisolver                1.0.1            py36hf484d3e_0  
lazy-object-proxy         1.3.1            py36h14c3975_2  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.34               hb9fc6fc_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.9                he85c1e1_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
lxml                      4.2.4                     <pip>
markupsafe                1.0              py36h14c3975_1  
matplotlib                2.2.2            py36h0e671d2_1  
mayavi                    4.6.2                     <pip>
mccabe                    0.6.1                    py36_1  
mistune                   0.8.3            py36h14c3975_1  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.4            py36h4414c95_1  
mkl_random                1.0.1            py36h4414c95_1  
mne                       0.16.2                    <pip>
mock                      2.0.0                     <pip>
more-itertools            4.3.0                    py36_0  
nbconvert                 5.3.1                    py36_0  
nbformat                  4.4.0                    py36_0  
ncurses                   6.1                  hf484d3e_0  
neo                       0.6.1                     <pip>
networkx                  1.9                       <pip>
nibabel                   2.3.0                     <pip>
nilearn                   0.4.2                     <pip>
nipype                    1.1.2                     <pip>
nitime                    0.7                       <pip>
notebook                  5.6.0                    py36_0  
numexpr                   2.6.8            py36hd89afb7_0  
numpy                     1.15.1           py36h1d66e8a_0  
numpy-base                1.15.1           py36h81de0dd_0  
numpydoc                  0.8.0                    py36_0  
olefile                   0.45.1                   py36_0  
openssl                   1.0.2p               h14c3975_0  
packaging                 17.1                     py36_0  
pandas                    0.23.4           py36h04863e7_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py36_1  
parso                     0.3.1                    py36_0  
patsy                     0.5.0                    py36_0  
pbr                       4.2.0                     <pip>
pcre                      8.42                 h439df22_0  
pexpect                   4.6.0                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    5.1.0            py36h3deb7b8_0  
pip                       10.0.1                   py36_0  
pluggy                    0.7.1            py36h28b3542_0  
prometheus_client         0.3.1            py36h28b3542_0  
prompt_toolkit            1.0.15                   py36_0  
prov                      1.5.0                     <pip>
psutil                    5.4.7            py36h14c3975_0  
ptyprocess                0.6.0                    py36_0  
py                        1.6.0                    py36_0  
pyasn1                    0.4.4            py36h28b3542_0  
pyasn1-modules            0.2.2                    py36_0  
pycodestyle               2.3.1            py36hf609f19_0  
pycparser                 2.18                     py36_1  
pydocstyle                2.1.1                     <pip>
pydot                     1.2.4                     <pip>
pydotplus                 2.0.2                     <pip>
pyface                    6.0.0                    py36_0  
pyflakes                  1.6.0                    py36_0  
pygments                  2.2.0                    py36_0  
PyHamcrest                1.9.0                     <pip>
pylint                    2.1.1                    py36_0  
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.2.0                    py36_1  
pyqt                      5.9.2            py36h751905a_0  
PyQt5                     5.11.2                    <pip>
PyQt5_sip                 4.19.12                   <pip>
pysocks                   1.6.8                    py36_0  
pysurfer                  0.8.0                     <pip>
pytest                    3.7.4                    py36_0  
pytest-cov                2.6.0                    py36_0  
pytest-faulthandler       1.5.0                     <pip>
pytest-forked             0.2                       <pip>
pytest-sugar              0.9.1                     <pip>
pytest-xdist              1.23.0                    <pip>
python                    3.6.6                hc3d631a_0  
python-dateutil           2.7.3                    py36_0  
python-picard             0.3                       <pip>
pytz                      2018.5                   py36_0  
pyzmq                     17.1.2           py36h14c3975_0  
qt                        5.9.5                h7e424d6_0  
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.4.1                    py36_0  
qtpy                      1.5.0                    py36_0  
quantities                0.12.2                    <pip>
rdflib                    4.2.2                     <pip>
readline                  7.0                  h7b6447c_5  
requests                  2.19.1                   py36_0  
rope                      0.11.0                   py36_0  
scikit-learn              0.19.1           py36hedc7406_0  
scipy                     1.1.0            py36hfa4b5c9_1  
secretstorage             3.1.0                    py36_0  
send2trash                1.5.0                    py36_0  
service_identity          17.0.0           py36h28b3542_0  
setuptools                40.2.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
simplejson                3.16.0                    <pip>
sip                       4.19.12          py36he6710b0_0  
six                       1.11.0                   py36_1  
snowballstemmer           1.2.1                    py36_0  
sphinx                    1.7.8                    py36_0  
sphinxcontrib             1.0                      py36_1  
sphinxcontrib-websupport  1.1.0                    py36_1  
spyder                    3.3.1                    py36_1  
spyder-kernels            0.2.6                    py36_0  
sqlite                    3.24.0               h84994c4_0  
statsmodels               0.9.0            py36h035aef0_0  
tbb                       2018.0.5             h6bb024c_0  
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                    py36_1  
testpath                  0.3.1                    py36_0  
tk                        8.6.8                hbc83047_0  
tornado                   5.1              py36h14c3975_0  
traitlets                 4.3.2                    py36_0  
traits                    4.6.0            py36h7b6447c_3  
traitsui                  6.0.0                    py36_1  
twisted                   18.7.0           py36h14c3975_1  
typed-ast                 1.1.0            py36h14c3975_0  
urllib3                   1.23                     py36_0  
vtk                       8.1.1                     <pip>
vtk                       8.1.0           py36h9686630_201  
wcwidth                   0.1.7                    py36_0  
webencodings              0.5.1                    py36_1  
wheel                     0.31.1                   py36_0  
widgetsnbextension        3.4.1                    py36_0  
wrapt                     1.10.11          py36h14c3975_2  
xz                        5.2.4                h14c3975_4  
zeromq                    4.2.5                hf484d3e_1  
zlib                      1.2.11               ha838bed_2  
zope                      1.0                      py36_1  
zope.interface            4.5.0            py36h14c3975_0  
(mne) pasca@pasca-XPS-13-9360:~/Tools/python/packages/neuropycon/examples$ 

```

**Comment by annapasca** [comment]
```
this is my output

`(mne) pasca@pasca-XPS-13-9360:~/Tools/python/packages/neuropycon/examples$ python run_power_analysis.py 
main_path /media/pasca/paska/meg_data/omega/sample_BIDS_omega/
*** main_path -> /media/pasca/paska/meg_data/omega/sample_BIDS_omega/ ***
180917-12:57:13,319 nipype.workflow INFO:
	 Workflow power_pipeline settings: ['check', 'execution', 'logging', 'monitoring']
180917-12:57:14,59 nipype.workflow INFO:
	 Running in parallel.
180917-12:57:14,71 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 14.00/14.00, Free processors: 3/3.
180917-12:57:14,146 nipype.workflow INFO:
	 [Node] Setting-up "power_pipeline.datasource" in "/media/pasca/paska/meg_data/omega/sample_BIDS_omega/power_pipeline/_sess_index_ses-0001_subject_id_sub-0003/datasource".
180917-12:57:14,151 nipype.workflow INFO:
	 [Node] Running "datasource" ("nipype.interfaces.io.DataGrabber")
180917-12:57:14,165 nipype.workflow INFO:
	 [Node] Finished "power_pipeline.datasource".
180917-12:57:16,69 nipype.workflow INFO:
	 [Job 0] Completed (power_pipeline.datasource).
180917-12:57:16,72 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 14.00/14.00, Free processors: 3/3.
180917-12:57:16,117 nipype.workflow INFO:
	 [Node] Setting-up "power_pipeline.power.power" in "/media/pasca/paska/meg_data/omega/sample_BIDS_omega/power_pipeline/power/_sess_index_ses-0001_subject_id_sub-0003/power".
180917-12:57:16,121 nipype.workflow INFO:
	 [Node] Running "power" ("ephypype.interfaces.mne.power.Power")
in Power
Opening raw data file /media/pasca/paska/meg_data/omega/sample_BIDS_omega/sub-0003/ses-0001/meg/sub-0003_task-rest_run-01_meg_raw_short_filt_dsamp_ica.fif...
/home/pasca/Tools/python/packages/neuropycon/ephypype/ephypype/power.py:18: RuntimeWarning: This filename (/media/pasca/paska/meg_data/omega/sample_BIDS_omega/sub-0003/ses-0001/meg/sub-0003_task-rest_run-01_meg_raw_short_filt_dsamp_ica.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
  epochs = read_raw_fif(data_fname, preload=True)
This filename (/media/pasca/paska/meg_data/omega/sample_BIDS_omega/sub-0003/ses-0001/meg/sub-0003_task-rest_run-01_meg_raw_short_filt_dsamp_ica.fif) does not conform to MNE naming conventions. All raw files should end with raw.fif, raw_sss.fif, raw_tsss.fif, raw.fif.gz, raw_sss.fif.gz or raw_tsss.fif.gz
    Read 5 compensation matrices
    Range : 0 ... 144000 =      0.000 ...   180.000 secs
Ready.
Current compensation grade : 3
Reading 0 ... 144000  =      0.000 ...   180.000 secs...
Effective window size : 0.320 (s)
(270, 48)
*** save /media/pasca/paska/meg_data/omega/sample_BIDS_omega/power_pipeline/power/_sess_index_ses-0001_subject_id_sub-0003/power/sub-0003_task-rest_run-01_meg_raw_short_filt_dsamp_ica-psds.npz ***
*** save /media/pasca/paska/meg_data/omega/sample_BIDS_omega/power_pipeline/power/_sess_index_ses-0001_subject_id_sub-0003/power/sub-0003_task-rest_run-01_meg_raw_short_filt_dsamp_ica-psds.png ***
180917-12:57:17,824 nipype.workflow INFO:
	 [Node] Finished "power_pipeline.power.power".
180917-12:57:18,70 nipype.workflow INFO:
	 [Job 1] Completed (power_pipeline.power.power).
180917-12:57:18,73 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 14.00/14.00, Free processors: 3/3.
180917-12:57:18,156 nipype.workflow INFO:
	 [Node] Setting-up "power_pipeline.power.power_band" in "/media/pasca/paska/meg_data/omega/sample_BIDS_omega/power_pipeline/power/_sess_index_ses-0001_subject_id_sub-0003/power_band".
180917-12:57:18,165 nipype.workflow INFO:
	 [Node] Running "power_band" ("ephypype.nodes.power_tools.PowerBand")
the .npz file contain ['psds', 'freqs'] 

psds is a matrix (270, 48) 

freqs contains 48 frequencies 

*** frequency band [2, 4] ***

*** frequency band [5, 7] ***

*** frequency band [8, 12] ***

*** frequency band [13, 29] ***

*** frequency band [30, 59] ***

*** frequency band [60, 90] ***

(270, 6)
180917-12:57:18,215 nipype.workflow INFO:
	 [Node] Finished "power_pipeline.power.power_band".
180917-12:57:20,72 nipype.workflow INFO:
	 [Job 2] Completed (power_pipeline.power.power_band).
180917-12:57:20,75 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 14.00/14.00, Free processors: 3/3.
(mne) pasca@pasca-XPS-13-9360:~/Tools/python/packages/neuropycon/examples$ 
```
`

**Comment by jasmainak** [comment]
@annapasca did you try using my environment file that I provided in [this comment](https://github.com/neuropycon/ephypype/issues/28#issuecomment-420666347)? You can save it in an `environment.yml` and create an environment:

```sh
$ conda env create -f environment.yml
```

Then activate the environment and run the command again ...

**Comment by jasmainak** [comment]
I suspect though that it's not related to the environment, just the data files. So, we should try to fix automatic dataset fetching. This is done in my pull request #30 . Let us test it and make it work ...

**Comment by jasmainak** [comment]
Okay I think this issue can be closed now.
