### ISSUE TITLE
deepcopy error when running workflow in python3

### ISSUE THREAD

**Issue by dmalt** [neuropycon/ephypype#5]
Can't make nipype work under python3.
I've created a simple pipeline  to disentangle command-line code from nipype and ephypype.
When I run the workflow I get the following error:

```Traceback (most recent call last):
  File "test_cli.py", line 91, in <module>
    workflow.run(plugin='Linear')
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 570, in run
    flatgraph = self._create_flat_graph()
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 830, in _create_flat_graph
    workflowcopy = deepcopy(self)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/dmalt/Code/python/neuropycon/npyc3/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle dict_keys objects```

It seems to me that something goes wrong with looped links inside the workflow object. The error appears when nipype tries to deepcopy the workflow instance.

In python2.7 the same works fine. I tried to google for similar problems but I got only one
google groups issue like that without responses.

Have you guys seen a problem like this?

**Comment by davidmeunier79** [comment]
I do not know if it is related to python 3.6 instead of 3.5 that we have tested with Annalisa, but I would not think so.

However, we have had issues with latest version of nipype 0.14, you should try to force the install of the version 0.13 through pip install, or  my version of nipype https://github.com/davidmeunier79/nipype

**Comment by dmalt** [comment]
I've tested both python3.5 and python3.6 and nipype0.12, nipype0.13 and nipype0.14. The issue
remains. 
I've found a similar problem in [one of the nipype's issues](https://github.com/nipy/nipype/issues/1752#issuecomment-267695376).  The guy reporting the problem says that it probably was about a conflict between python2 and python3 in anaconda env. It doesn't seem to be the case though since I've tried several anaconda virtualenv configurations --- still no success. I've posted a question to the related issue thread in nipype so may be they could help.
There's also [another thread](https://github.com/whit537/cloud-custodian/pull/22) that should be related to ours. It suggests that it's not a packages configuration issue.
It seems to me that the problem is either in a way that I assemble the pipeline or in the data I use it on. It works on python2.7 though.

**Comment by dmalt** [comment]
@davidmeunier79: Maybe I can  send a code snippet that runs the pipeline together with the chunk of data, so we can see if the problem is in my setup or it's something else?

**Comment by dmalt** [comment]
Oh, I just figured it out.
In my pipeline I used dictionary keys as an iterable to the pipeline (it's part of cli code to handle paths to input files in parallel). Apparently in python3 you have to wrap dict.keys() in list() --- otherwise the deepcopy issue appears.

**Comment by ostanley** [comment]
@dmalt Can you elaborate on your solution for this a bit? I think I have the same issue. I am initializing nodes in a for loop and storing them as keys in a dictionary, and getting this error as well.
